name: Examples
on: 
  schedule:
  - cron: "0 2 * * 1,3,5,0"
  workflow_dispatch:

env: 
  JAVA_OPTS: "-Xmx4G"
  JVM_OPTS: "-Xmx4G"
  SBT_OPTS: "-Xmx4G"

jobs:
  unix_build:
    name: Examples
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-11
            llvm_bin_path: /usr/local/opt/llvm@13/bin

          - os: ubuntu-20.04
            llvm_bin_path: /usr/lib/llvm-13/bin

    runs-on: ${{ matrix.os }}
    env:
      SN_RELEASE: fast
      LLVM_VERSION: 13
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: '17'
          cache: 'sbt'


      - name: Setup Unix-like
        run: ./build/setup_unix.sh

      - name: Build
        run: sbt devPublish versionDump
        env: 
          LLVM_BIN: ${{ matrix.llvm_bin_path }}

      - name: Setup for examples
        run: |
          git clone https://github.com/keynmol/sn-bindgen-examples examples
          cd examples 
          ./manual_setup.sh

          PLATFORM="$(uname)"
          if [ $PLATFORM == "Darwin" ]; then 
            echo "It's a Mac"
          else
            docker run -p 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword -d postgres
            docker run -p 6379:6379 -d redis
          fi

      - name: Cache sbt-vcpkg
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/sbt-vcpkg
            ~/.cache/sbt-vcpkg
          key: ${{ runner.os }}-sbt-vcpkg-${{ hashFiles('examples/**/*.sbt') }}

      - name: Run examples
        env: 
          LLVM_BIN: ${{ matrix.llvm_bin_path }}
        run: | 
          PLATFORM="$(uname)"

          export SN_BINDGEN_VERSION="$(cat version)"

          cd examples
          sbt runExamples


